### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mshaikh786** [ahay/src#188]
:bug:  Bug report

**Issues with running make after configure**

I am seeing the following error when running make after successful configure step. 
I am compiling on CrayXC 40 with Intel compilers.
```
shaima0d@cdl2:/project/k01/shaima0d/tickets/29944/src> ./configure 
checking for Python ... /sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0/bin/python
checking Python version ... 3.8.0
checking for RSFROOT ... no

I am setting RSFROOT to /sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0

checking for SCons ... /home/shaima0d/.local/bin/scons
checking SCons version ... v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691
Running RSFROOT=/sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0 /home/shaima0d/.local/bin/scons  config ...
------------------------
scons: Reading SConscript files ...
checking platform ... (cached) posix [unknown]
checking for C compiler ... (cached) /opt/cray/pe/craype/2.6.3/bin/cc
checking if /opt/cray/pe/craype/2.6.3/bin/cc works ... yes
checking for ar ... (cached) ar
checking for libraries ... ['m']
checking complex support ... yes
checking for X11 headers ... /usr/include
checking for X11 libraries ... /usr/lib/X11
checking for OpenGL ... no
checking for sfpen ... (cached) xtpen
checking for ppm ... yes
checking for tiff ... yes
checking for GD (PNG) ... no

  gdpen will not be built.
checking for plplot ... no
checking for ffmpeg ... no
checking for cairo (PNG) ... yes
checking for cairo (SVG) ... yes
checking for cairo (PDF) ... yes
checking for jpeg ... yes
checking for BLAS ... yes
checking for LAPACK ... yes
checking for SWIG ... (cached) no
checking for numpy ... (cached) yes
checking API options ... (cached) []
checking for C++ compiler ... (cached) /opt/cray/pe/craype/2.6.3/bin/CC
checking if /opt/cray/pe/craype/2.6.3/bin/CC works ... yes
checking for MPICC ... (cached) cc
checking if cc works ... yes
checking for MPICXX ... (cached) CC
checking if CC works ... yes
checking for MPIRUN ... (cached) srun
checking for Posix threads ... yes
checking for OpenMP ... yes
checking for CUDA ... (cached) no
checking for FFTW ... no
checking for SuiteSparse ... no
scons: done reading SConscript files.
scons: Building targets ...
shell_script(["env.sh"], [])
shell_script(["env.csh"], [])
scons: done building targets.
------------------------
Done with configuration.
shaima0d@cdl2:/project/k01/shaima0d/tickets/29944/src> make VERBOSE=1
RSFROOT=/sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0 PYTHONPATH=/sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0/lib/python3.8/site-packages:/home/shaima0d/.local/lib/python3.8/site-packages/scons:/sw/xc40cle7/python/3.8.0/sles15_gnu8.3.0/lib/python3.8/site-packages:/home/shaima0d/.local/lib/python3.8/site-packages /home/shaima0d/.local/bin/scons
scons: Reading SConscript files ...
AttributeError: 'dict' object has no attribute 'insert':
  File "/lustre/project/k01/shaima0d/tickets/29944/src/SConstruct", line 135:
    SConscript(dirs=build,name='SConscript',exports=frame_exports)
  File "/home/shaima0d/.local/lib/python3.8/site-packages/scons/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/home/shaima0d/.local/lib/python3.8/site-packages/scons/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/shaima0d/.local/lib/python3.8/site-packages/scons/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/lustre/project/k01/shaima0d/tickets/29944/src/build/framework/doc/SConscript", line 7:
    env.Append(ENV={'LD_LIBRARY_PATH':os.environ.get('LD_LIBRARY_PATH')})
  File "/home/shaima0d/.local/lib/python3.8/site-packages/scons/SCons/Environment.py", line 1183:
    val.insert(0, orig)
make: *** [Makefile:4: all] Error 2
```

**To Reproduce**
Here is my environment settings in SConstruct:
env = Environment(ENV=os.environ,
CC='/opt/cray/pe/craype/2.6.3/bin/cc',
CXX='/opt/cray/pe/craype/2.6.3/bin/CC',
CCFLAGS=' -mkl -openmp -O2 -DHAVE_MKL',
OMP='True',
LINKFLAGS=' -mkl -openmp -O2',
MPICC='cc',
MPICXX='CC',
MPIRUN='srun',
)
1. Amend the SConstruct to add the environment settings.
2. Run configure
3. Run make
4. Error reported:
AttributeError: 'dict' object has no attribute 'insert' .....(as above)

**Expected behavior**
With default environment setting, I.e. using system gcc, the make runs past the issue. 
**Screenshots**

**Desktop (please complete the following information):**

- OS: CLE7.01 (SLES15)
 -Using git master branch of madagascar.

**Additional context**

**Comment by pplotn** [comment]
Hi, Mohammed! How is your success in kaust with it?  Can you install Madagascar on vlogin?

**Comment by mshaikh786** [comment]
> Hi, Mohsin! How is your success in kaust with it? Can you install Madagascar on vlogin?

Hello Pavel
As you can see, there hasn't been any input from the developer as yet.
I can surely try on vlogin. Can you please submit this request to help@hpc.kaust.edu.sa ?

**Comment by zhichenggeng** [comment]
@mshaikh786 Hi, can you try to use python 3.7 with scons 3.0.5? I don't know if scons 3.1.2 is a stable version working well with 3.8. But I'm sure scons 3.0.5 works well with python 3.7.

**Comment by mshaikh786** [comment]
Coincidently, I am attempting to do the same as we speak. I guess the key you mentioned in python/3.7 . I have been using Python/3.8.0 and for some reason, it appears that scons 3.x didn't like agree with it. 
Will add further details how it goes.

**Comment by pplotn** [comment]
Hello, Mohsin
I created ticket # 30199 on ibex@hpc.kaust.edu.sa

related to installation of Madagascar on ibex to use with gpu.
It has a lot of good codes using cuda on gpu. So our group Seismic wave
analysis group will be very thankful, if it's possible to make.

my kaust email is pavel.plotnitskii@kaust.edu.sa


*HERE is the ticket*
Re: [Supercomputing Lab #30199]

This message has been automatically generated in response to the creation
of a ticket regarding , a summary of which appears below.

There is no need to reply to this message right now. Your ticket has been
assigned an ID of *[Supercomputing Lab #30199]*.

Please include the string *[Supercomputing Lab #30199]* in the subject line
of all future correspondence about this issue. To do so, you may reply to
this message.

Thank you,
cluster-apps-reply@hpc.kaust.edu.sa
------------------------------
Hello, I have a question about usage of gpu on ilogin

it seems it have Madagascar module , which I need.
But I can use gpu there?

Seems from description that I can.

* Table 1. Ibex CPU Resources*

*Haswell*

cpu_intel_e5_2699_v3 (gpu)
Regards, Pavel

0545469767

сб, 28 мар. 2020 г. в 17:18, Mohsin Ahmed Shaikh <notifications@github.com>:

**Comment by mshaikh786** [comment]
Using Python/3.7.0 and with scons provided within the repo i.e. 3.0.5, I am still seeing the same issue. 

- The source was clone from the GitHub,
```
commit 4883d27e8c37ab4ff92e6b8341791fc84131c862 (HEAD -> master, origin/master, origin/HEAD)
Author: chenyk1990 <chenyk1990@gmail.com>
Date:   Sat Mar 28 22:24:48 2020 -0500
```

    addgpucode

- Following is added in SConstruct for CrayXC environment: 

```
env = Environment(ENV=os.environ)
env['CC']='cc'
env['CXX']='CC'
env['MPICC']='cc'
env['MPICXX']='CC',
env['CCFLAGS']='-mkl -qopenmp -O2 -DHAVE_MKL'
env['LINKFLAGS']='-mkl -qopenmp -O2'
env['API'] = 'python,C++'
env['MPIRUN']='srun'
```
- Configure completed successful (file attached)
[config.log](https://github.com/ahay/src/files/4398474/config.log)

- make attempted and failed with a scons error:
`shaima0d@cdl5:/project/k01/shaima0d/tickets/29944/src> make all
RSFROOT=/project/k01/shaima0d/tickets/29944/install/md2.0_py3 PYTHONPATH=/project/k01/shaima0d/tickets/29944/install/md2.0_py3/lib/python3.7/site-packages:/project/k01/shaima0d/software/cle7up01/apps/intelpython3/lib/python3.7/site-packages:/sw/xc40cle7/xalt/1.1.2/sles15.0_gcc8.3.0/site:/sw/xc40cle7/xalt/1.1.2/sles15.0_gcc8.3.0/libexec /project/k01/shaima0d/tickets/29944/install/md2.0_py3/bin/scons
scons: Reading SConscript files ...
AttributeError: 'dict' object has no attribute 'insert':
  File "/lustre/project/k01/shaima0d/tickets/29944/src/SConstruct", line 136:
    SConscript(dirs=build,name='SConscript',exports=frame_exports)
  File "/lustre/project/k01/shaima0d/tickets/29944/install/md2.0_py3/lib/scons/SCons/Script/SConscript.py", line 668:
    return method(*args, **kw)
  File "/lustre/project/k01/shaima0d/tickets/29944/install/md2.0_py3/lib/scons/SCons/Script/SConscript.py", line 605:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/lustre/project/k01/shaima0d/tickets/29944/install/md2.0_py3/lib/scons/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/lustre/project/k01/shaima0d/tickets/29944/src/build/framework/doc/SConscript", line 7:
    env.Append(ENV={'LD_LIBRARY_PATH':os.environ.get('LD_LIBRARY_PATH')})
  File "/lustre/project/k01/shaima0d/tickets/29944/install/md2.0_py3/lib/scons/SCons/Environment.py", line 1175:
    val.insert(0, orig)
make: *** [Makefile:4: all] Error 2
`
I'm a bit confused with the error description itself. Is it a wrong use of the datatype?
AttributeError: 'dict' object has no attribute 'insert':

**Comment by pplotn** [comment]
Hi, Mohsin!  What I can say from my point of view, is that you need also to
install some prerequisites,   for example, fftw3, blas, lapack. If
configure does not recognize them properly (check config.log, config.py for
that) your make will crash definitely.

**Comment by mshaikh786** [comment]
Hi Pavel, BLAS and LAPACK are being discovered successfully from MKL. I can add FFTW to the environment but this issue has to do with the Scons in Python3 implementation of the build recipe. 

Regards

--

Mohsin Ahemd Shaikh

**Comment by pplotn** [comment]
And it would be great if we can install Madagascar within python 3
interpreter. It's possible on work station, but not sure about cray

**Comment by mshaikh786** [comment]
That’s exactly what we are debugging. As you can see in the bug report I have attached in the issue API python,C++ have been chosen. 
The issue is in the scons SConstruct where it updates the LD_LIBRARY_PATH. Scons is calling a method called “insert” on a Datatype “dict” i.e. a dictionary, where this method doesn’t exit for dictionaries. 

I am sure the developer will be able to debug this issue. 

 

Regards

--

Mohsin Ahemd Shaikh

**Comment by pplotn** [comment]
Also as I understand from config.log   swig was not recognised. As i
remember it is also imporatant as scons and python (On workstation I used
python  3.7.3, swig 3.0.12). To do that you can include it in configure
command  *(SWIG=swig)*:
./configure API=c++,python SWIG=swig   --prefix=/home/plotnips/Madagascar

scons: Configure: checking for SWIG ...
scons: Configure: (cached) no


Hope that helps
Regards, Pavel

вс, 29 мар. 2020 г. в 12:30, Mohsin Ahmed Shaikh <notifications@github.com>:

**Comment by zhichenggeng** [comment]
@mshaikh786 Hi, I don't know why you add the following to your `SConstruct`. Madagascar should be able to detect all these automatically. 
```
env = Environment(ENV=os.environ)
env['CC']='cc'
env['CXX']='CC'
env['MPICC']='cc'
env['MPICXX']='CC',
env['CCFLAGS']='-mkl -qopenmp -O2 -DHAVE_MKL'
env['LINKFLAGS']='-mkl -qopenmp -O2'
env['API'] = 'python,C++'
env['MPIRUN']='srun'
```
I add the first three lines to my `SConstruct` and finally I get the same error. After I delete `ENV=os.environ`, the bug is solved. I would suggest you try that.

**Comment by mshaikh786** [comment]
For Crays you need to import the environment to enable your build to use Cray compiler wrappers which gives you access to the Cray programming environment. Without updating the environment, e.g. the cc compiler will be pointing to /usr/bin/cc which is system's gcc-7 and not /opt/cray/pe/craype/2.6.3/bin/cc which wrapps the Intel compiler with cross compiling and performance flags and also brings the libraries e.g. intel_mpich, mkl, and many others. I suspect your case above where you took out ENV=os.environ would have picked up /usr/bin/cc on Shaheen. 

Coming to how to fix the issue at hand. As I suspected, it was an issue with the datatype. Looking closely at the error scons, it appears that your SConscript in "/lustre/project/k01/shaima0d/tickets/29944/src/build/framework/doc/SConscript" on line 7 references ENV as a dictionary. 
Passing ENV=os.environ actually passes ENV as a type of class<environ> which is not a dictionary. This confuses scons downstream. The fix to this would be to pass the default Cray environment as a dictionary and then to add the variables of interest to the environemnt. Adding the following to SConstruct has worked for me:

ENV=dict()
for i in os.environ:
   ENV[i]=os.environ[i]
env = Environment(ENV=ENV)
env['CC']='cc'
env['CXX']='CC'
env['MPICC']='cc'
env['MPICXX']='CC'
env['CCFLAGS']='-mkl'
env['CPPDEFINES']=['HAVE_MKL']
env['OMP']='True'
env['LINKFLAGS']='-mkl -qopenmp -O2'
env['API'] = 'python,C++'
env['MPIRUN']='srun'


Ideally if I were developing, I would look for handelling this corner case more elegantly e.g. defining CrayXC as a platform, but I am no expert of scons. 
I guess we can close this issue now that there is atleast one solution. 
I will probably open another issue with building with CUDA where nvcc is picking up a flag that it doesn't support.
